# Use the slim python 3.12 image
FROM python:3.12-slim

# Ensure output is unbuffered
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libportaudio2 \
    python3-dev \
    build-essential \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the requirements.txt /app/requirements.txt
COPY src/edge_devices/scribe_device/requirements.txt /app/resources/requirements.txt
RUN pip install --no-cache-dir -r /app/resources/requirements.txt

# Copy the developer modules
COPY src/edge_devices/scribe_device/stt_processor.py /app/scribe/stt_processor.py
COPY src/edge_devices/scribe_device/utils.py /app/scribe/utils.py
COPY src/edge_devices/scribe_device/run_scribe.py /app/scribe/run_scribe.py

# Run the edge device set up script
CMD ["python", "/app/scribe/stt_processor.py"]

