# Use the slim Python 3.12 image
FROM python:3.12-slim

# Optional: Ensure output is unbuffered (good for logging)
ENV PYTHONUNBUFFERED=1

# Install system dependencies, including libgomp1 for lightgbm
RUN apt-get update && apt-get install -y libgomp1 && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Ensure the search engine data directory exists
RUN mkdir -p /app/icd_10_search_eng_data

# Copy the requirements file and install dependencies
COPY src/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the search engine source code into the container
COPY src/search_engine/ /app/search_engine/

# Copy the stop words file into the search engine data directory
COPY src/search_engine/data/stopwords.txt /app/stopwords.txt
COPY src/search_engine/data/train_data_edited.csv /app/train_data_edited.csv

# Build the Title Index, Main Index and the Learn2Rank Model
CMD ["python", "search_engine/build_search_engine.py"]
