# Use the slim Python 3.12 image
FROM python:3.12-slim

# Optional: Ensure output is unbuffered (good for logging)
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY src/search_engine/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy over developer modules
COPY src/ai_p

# Copy the search engine source code into the container
COPY src/ai_pipeline/ /app/ai_pipeline/

CMD ["python", "/app/front_end_application.py"]