version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - "/var/lib/aiinabox/ollamadata:/root/.ollama"
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: "NVIDIA-GPU"
                value: 3
      restart_policy:
        condition: any

  icd_10_code_scraping:
    image: 192.168.40.187:5001/docker-icd_10_code_scraping:latest
    volumes:
      - /var/lib/aiinabox/scraped_data/jsons:/app/icd_10_code_jsons
      - /var/lib/aiinabox/scraped_data/codes:/app/icd_10_codes
      - /var/lib/aiinabox/scraped_data/codes_clean:/app/icd_10_codes_clean
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.hardware == server

  icd_10_search_engine:
    image: 192.168.40.187:5001/docker-icd_10_search_engine:latest
    volumes:
      - /var/lib/aiinabox/scraped_data/jsons:/app/icd_10_code_jsons
      - /var/lib/aiinabox/scraped_data/codes_clean:/app/icd_10_codes_clean
      - /var/lib/aiinabox/search_eng_data:/app/icd_10_search_eng_data
      - /var/lib/aiinabox/index_dir:/app/icd_10_index_dir
      - /var/lib/aiinabox/title_index_dir:/app/icd_10_title_index_dir
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.hardware == server

  front_end:
    image: 192.168.40.187:5001/docker-front_end:latest
    ports:
      - "5000:5000"
    volumes:
      - /var/lib/aiinabox/front_end:/app/front_end:ro
      - /var/lib/aiinabox/search_eng_data:/app/icd_10_search_eng_data:ro
      - /var/lib/aiinabox/index_dir:/app/icd_10_index_dir:ro
      - /var/lib/aiinabox/title_index_dir:/app/icd_10_title_index_dir:ro
    deploy:
      placement:
        constraints:
          - node.labels.hardware == server
    scribe_consumer:
      image: 192.168.40.187:5001/docker-scribe_consumer:latest
      environment:
        - MQTT_BROKER_HOST=192.168.40.187
        - MQTT_BROKER_PORT=1883
        - MQTT_USER=mqttuser
        - MQTT_PASS=ballerselite40
        - MQTT_TOPIC=scribe/transcripts
        - FRONTEND_URL=http://front_end:5000/api/transcript
      deploy:
        restart_policy:
          condition: on-failure
        placement:
          constraints:
            - node.labels.hardware == server 

networks:
  default:
    driver: overlay
    attachable: true
