# Use the slim python 3.9 image
FROM python:3.9-slim

# Ensure output is unbuffered
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libportaudio2 \
    python3-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrage pip
RUN pip install RPi.GPIO sounddevice numpy git+https://github.com/openai/whisper.git

# Set the working directory
WORKDIR /app

# Copy the requirements.txt /app/requirements.txt
COPY src/requirements.txt /app/resources/requirements.txt
RUN pip install --no-cache-dir -r /app/resources/requirements.txt

# Copy the developer modules
COPY src/stt_processor.py /app/scribe/stt_processor.py
COPY src/utils.py /app/scribe/utils.py
COPY src/run_scribe.py /app/scribe/run_scribe.py

# Run the edge device set up script
CMD ["python", "/app/scribe/run_scribe.py"]

